apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
      - name: c1
        image: ubuntu
        command: ["/bin/bash","-c","sleep 5000"]
        volumeMounts:
          - name: v1
            mountPath: "/tmp/test"
      - name: c2
        image: centos
        command: ["/bin/bash","-c","sleep 5000"]
        volumeMounts:
          - name: v1
            mountPath: "/tmp/check"
  volumes:
    - name: v1
      emptyDir: {}

