apiVersion: v1
kind: Pod
metadata:
  name: myenvconfig
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo helooo; sleep 5; done"]
      env:
       - name: CMENV
         valueFrom:
            configMapKeyRef:
              name: cmvol
              key: sample.conf
