apiVersion: v1
kind: Pod
metadata: 
  name: envsecret
spec:
   containers:
     - name: c1
       image: centos
       command: ["/bin/bash","-c","while true; do echo hello; done"]
       env:
         - name: USER
           valueFrom:
               secretKeyRef:
                 name: secret1
                 key: user.txt
         - name: Pass
           valueFrom:
              secretKeyRef:
                name: secret1
                key: pass.txt
