apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
    - name: c1
      image: nginx
      volumeMounts:
        - name: host-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: host-volume
      hostPath:
        path: /home/apmosys/k8s
        type: DirectoryOrCreate  # Will create the directory if it doesn't exist

