kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo Hello; sleep 5; done"]
    - name: c01
      image: ubuntu
      command: ["/bin/bash","-c","while true; do echo Kubeit; sleep 5; done"]
  restartPolicy: Never
